In [4]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

result = A + B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nResultant Matrix (A + B):\n", result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Resultant Matrix (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
